### ISSUE TITLE
redesign - overview issue

### ISSUE THREAD

**Issue by gavanderhoorn** [gavanderhoorn/universal_robot#1]
Aggregating all separate issues here:

 - [x] rename metapackage (`universal_robot` -> `universal_robots`): fce430f500766a882c5248329378c0b08987d9e4

 - [ ] consider renaming repository as well

 - [ ] align package manifests and `CMakeLists.txt` with other ROS-I (robot support) packages

 - [ ] redo `description` package:
   - sort out xacros and upgrade xacro usage to Jade+ (default args, yaml parameters, etc):
      - use proper xacro namespacing to 'hide' variant-specific params
      - make it easier for users to use their own *calibrated* D-H values by storing parameters in `.yaml` file instead of hard-coding in the xacro itself
      - keep nr of default params as low as possible (use yaml to support custom joint limits)
      - prefix models with `ur_` or `universal_robots_` (need to decide)
      - use `joint_N` and `link_N` naming for `joint`s and `link`s
      - check `base`, `tool0` and `flange` frames
      - remove `ee_link`
      - fix `base_link` 180 degree rotation wrt UR base coordinate frame (check `-pi` rotation between `base` and `base_link`)
      - consider adding `tool0_controller` floating frame (`ur_modern_driver`)
   - add top-level `.xacro` and `_macro.xacro` files
   - resolve `2pi` joint limit problem on elbow joint (or look at the IK additions that were submitted in recent PRs to `universal_robot`)
   - remove Gazebo specific bits as much as possible (should go in a separate pkg?):
      - do not include a `world` frame by default (complicates composition)
      - remove Gazebo materials, `gazebo_ros_control` plugin
      - only leave `dynamics` and `inertial` elements
      - no `transmission` elements
   - add `roslaunch` tests

 - [ ] redo `ur_gazebo` package (setup like a driver, but just a virtual one):
    - add 'overlay' top-level `.xacro` and `_macro.xacro` that add Gazebo-specific elements (transmissions, `gazebo_ros_control`, materials, etc: use `link` references)
    - add `load` and `test` launch files
   - add `roslaunch` tests
   - support specifying different `hardwareInterface` values in `transmission` elements for Gazebo (ros-industrial/universal_robot#227). Use Yaml for that, instead of yet another conditional.

 - [ ] upgrade MoveIt configurations:
   - recreate using newest MSA
   - use `trac_ik` by default
   - use ROS-I compliant naming for groups, virtual joints and group states
   - add `moveit_planning_execution.launch` file:
     - include support for running with `industrial_robot_simulator`
   - add `roslaunch` tests

 - [ ] revive / polish / fixup `ur_kinematics` (check latest PRs)

 - [x] remove defunct `ur_driver` package: 7e8a1627248c49b642b0dcacd090a2d08b38432f

 - [ ] decide what to do with `ur_msgs`

'Stretch goals':

 - see if new Jade+ xacro functionality can be used to support 'plugin' xacro snippets that would make supporting things like the "Xamla rounded cap" possible without having to add special cases everywhere

**Comment by gavanderhoorn** [comment]
This is a wip, feel free to post suggestions.

**Comment by gavanderhoorn** [comment]
@Jmeyer1292

**Comment by Jmeyer1292** [comment]
I would consider

- Changing the default action server name to match other repositories
- Changing the driver launch structure to better match other repositories (e.g. currently it starts a robot_state_publisher in the driver launch files).

**Comment by Jmeyer1292** [comment]
Would we create different packages for the UR3, UR5, and UR10? Or still keep them concentrated in `ur_description`?

**Comment by Jmeyer1292** [comment]
Oh my gosh, I just looked up the loading a XACRO property through a yaml file! That's amazingly useful.

**Comment by gavanderhoorn** [comment]
@Jmeyer1292 wrote:
> - Changing the default action server name to match other repositories
> - Changing the driver launch structure to better match other repositories (e.g. currently it starts a robot_state_publisher in the driver launch files). 

both good ideas.

I invited you as a collaborator on this repository, so you should be able to edit the OP.

**Comment by gavanderhoorn** [comment]
@Jmeyer1292 wrote:
> Would we create different packages for the UR3, UR5, and UR10? Or still keep them concentrated in `ur_description`?

As they are essentially variants of each other, I think I'd be in favour of keeping them in one package.

The product naming of UR is a bit 'unfortunate' for us though: they don't really have model names, and their variant ids are just nrs. If we apply normal ros-i rules, we'd end up with `universal_robots_ur3` (or `ur_ur3`) for variant names, and a `universal_robots_ur_support` (or `ur_ur_support`).

I'm not sure yet what the best naming would be.

**Comment by gavanderhoorn** [comment]
@shaun-edwards, @levi-armstrong: I'm looking for some input on the naming. Should we follow regular conventions and so have names like `ur_ur3`, `ur_ur5` (or `universal_robots_ur3`)? Or stick with `ur3`, `ur5` and `ur10` as they are now?

I'm starting to like at least prefixing with `ur_` more and more. It would be consistent and if UR ever comes out with anything else that is not of the UR series we'd be able to incorporate that easily.

**Comment by jacknlliu** [comment]
Two considerations:
- config files can be easily applied to the multi-robots context  (for simulation and real)
- add cartesian space control test launch file

**Comment by gavanderhoorn** [comment]
Hi, thanks for your input.

> config files can be easily applied to the multi-robots context (for simulation and real)

Could you clarify this suggestion a bit? What exactly do you mean with "config files"?

> add cartesian space control test launch file

I'm also uncertain what you are after with this one: would this be a `test_move.py` but with MoveIt between the driver and the script, planning to pose goals? The driver itself doesn't support any "Cartesian .. control".

**Comment by gavanderhoorn** [comment]
Some experimental work: [gavanderhoorn/ur_ur_support](https://github.com/gavanderhoorn/ur_ur_support).
